// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagement.DataAccess;

#nullable disable

namespace VisitorManagement.API.Migrations
{
    [DbContext(typeof(VisitorCategoryDBContext))]
    [Migration("20230511014544_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitorManagement.Models.VisitorCategoryDetails", b =>
                {
                    b.Property<int>("VisitorCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorCategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorCategoryId");

                    b.ToTable("VisitorCategoryDetail");
                });

            modelBuilder.Entity("VisitorManagement.Models.Visitordetails", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitorCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("VisitorFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorId");

                    b.HasIndex("VisitorCategoryId");

                    b.ToTable("Visitordetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.Visitordetails", b =>
                {
                    b.HasOne("VisitorManagement.Models.VisitorCategoryDetails", "VisitorCategoryDetails")
                        .WithMany("Visitordetails")
                        .HasForeignKey("VisitorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorCategoryDetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.VisitorCategoryDetails", b =>
                {
                    b.Navigation("Visitordetails");
                });
#pragma warning restore 612, 618
        }
    }
}
