// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagement.DataAccess;

#nullable disable

namespace VisitorManagement.API.Migrations
{
    [DbContext(typeof(VisitorCategoryDBContext))]
    [Migration("20230513130847_startmigration")]
    partial class startmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitorManagement.Models.ResidentDetails", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flatnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidentId");

                    b.ToTable("ResidentDetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.VisitorCategoryDetails", b =>
                {
                    b.Property<int>("VisitorCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("categoryDescription")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("VisitorCategoryId");

                    b.ToTable("VisitorCategoryDetail");
                });

            modelBuilder.Entity("VisitorManagement.Models.VisitorLogsDetails", b =>
                {
                    b.Property<int>("VisitorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorLogId"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SpentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("VisitorLogId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("VisitorId");

                    b.ToTable("VisitorLogsDetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.Visitordetails", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitorCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("VisitorFirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VisitorLastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("VisitorId");

                    b.HasIndex("VisitorCategoryId");

                    b.ToTable("Visitordetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.VisitorLogsDetails", b =>
                {
                    b.HasOne("VisitorManagement.Models.ResidentDetails", "ResidentDetails")
                        .WithMany("LogDetails")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagement.Models.Visitordetails", "visitordetails")
                        .WithMany("VisitorLog")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentDetails");

                    b.Navigation("visitordetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.Visitordetails", b =>
                {
                    b.HasOne("VisitorManagement.Models.VisitorCategoryDetails", "VisitorCategoryDetails")
                        .WithMany("Visitordetails")
                        .HasForeignKey("VisitorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorCategoryDetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.ResidentDetails", b =>
                {
                    b.Navigation("LogDetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.VisitorCategoryDetails", b =>
                {
                    b.Navigation("Visitordetails");
                });

            modelBuilder.Entity("VisitorManagement.Models.Visitordetails", b =>
                {
                    b.Navigation("VisitorLog");
                });
#pragma warning restore 612, 618
        }
    }
}
